[project]
name = "b4b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.121.2",
    "httpx>=0.28.1",
    "pillow>=12.0.0",
    "pyhaproxy>=0.3.7",
    "redis>=7.1.0",
    "uvicorn>=0.38.0",
]
